//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.03.15 at 12:19:21 PM CET 
//


package com.bytemeistercoding.opcua.uanodeset;

import javax.xml.bind.annotation.*;
import javax.xml.datatype.XMLGregorianCalendar;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for ModelTableEntry complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="ModelTableEntry">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="RolePermissions" type="{http://opcfoundation.org/UA/2011/03/UANodeSet.xsd}ListOfRolePermissions" minOccurs="0"/>
 *         &lt;element name="RequiredModel" type="{http://opcfoundation.org/UA/2011/03/UANodeSet.xsd}ModelTableEntry" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="ModelUri" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="XmlSchemaUri" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="Version" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="PublicationDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *       &lt;attribute name="ModelVersion" type="{http://opcfoundation.org/UA/2011/03/UANodeSet.xsd}ModelVersion" />
 *       &lt;attribute name="AccessRestrictions" type="{http://opcfoundation.org/UA/2011/03/UANodeSet.xsd}AccessRestriction" default="0" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ModelTableEntry", propOrder = {
        "rolePermissions",
        "requiredModel"
})
public class ModelTableEntry {

    @XmlElement(name = "RolePermissions")
    protected ListOfRolePermissions rolePermissions;
    @XmlElement(name = "RequiredModel")
    protected List<ModelTableEntry> requiredModel;
    @XmlAttribute(name = "ModelUri", required = true)
    protected String modelUri;
    @XmlAttribute(name = "XmlSchemaUri")
    protected String xmlSchemaUri;
    @XmlAttribute(name = "Version")
    protected String version;
    @XmlAttribute(name = "PublicationDate")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar publicationDate;
    @XmlAttribute(name = "ModelVersion")
    protected String modelVersion;
    @XmlAttribute(name = "AccessRestrictions")
    protected Integer accessRestrictions;

    /**
     * Gets the value of the rolePermissions property.
     *
     * @return possible object is
     * {@link ListOfRolePermissions }
     */
    public ListOfRolePermissions getRolePermissions() {
        return rolePermissions;
    }

    /**
     * Sets the value of the rolePermissions property.
     *
     * @param value allowed object is
     *              {@link ListOfRolePermissions }
     */
    public void setRolePermissions(ListOfRolePermissions value) {
        this.rolePermissions = value;
    }

    /**
     * Gets the value of the requiredModel property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the requiredModel property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRequiredModel().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ModelTableEntry }
     */
    public List<ModelTableEntry> getRequiredModel() {
        if (requiredModel == null) {
            requiredModel = new ArrayList<ModelTableEntry>();
        }
        return this.requiredModel;
    }

    /**
     * Gets the value of the modelUri property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getModelUri() {
        return modelUri;
    }

    /**
     * Sets the value of the modelUri property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setModelUri(String value) {
        this.modelUri = value;
    }

    /**
     * Gets the value of the xmlSchemaUri property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getXmlSchemaUri() {
        return xmlSchemaUri;
    }

    /**
     * Sets the value of the xmlSchemaUri property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setXmlSchemaUri(String value) {
        this.xmlSchemaUri = value;
    }

    /**
     * Gets the value of the version property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setVersion(String value) {
        this.version = value;
    }

    /**
     * Gets the value of the publicationDate property.
     *
     * @return possible object is
     * {@link XMLGregorianCalendar }
     */
    public XMLGregorianCalendar getPublicationDate() {
        return publicationDate;
    }

    /**
     * Sets the value of the publicationDate property.
     *
     * @param value allowed object is
     *              {@link XMLGregorianCalendar }
     */
    public void setPublicationDate(XMLGregorianCalendar value) {
        this.publicationDate = value;
    }

    /**
     * Gets the value of the modelVersion property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getModelVersion() {
        return modelVersion;
    }

    /**
     * Sets the value of the modelVersion property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setModelVersion(String value) {
        this.modelVersion = value;
    }

    /**
     * Gets the value of the accessRestrictions property.
     *
     * @return possible object is
     * {@link Integer }
     */
    public int getAccessRestrictions() {
        if (accessRestrictions == null) {
            return 0;
        } else {
            return accessRestrictions;
        }
    }

    /**
     * Sets the value of the accessRestrictions property.
     *
     * @param value allowed object is
     *              {@link Integer }
     */
    public void setAccessRestrictions(Integer value) {
        this.accessRestrictions = value;
    }

}
