//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.03.15 at 12:19:21 PM CET 
//


package com.bytemeistercoding.opcua.uanodeset;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for NodeSetStatus complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="NodeSetStatus">
 *   &lt;simpleContent>
 *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *       &lt;attribute name="Code" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" default="0" />
 *     &lt;/extension>
 *   &lt;/simpleContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "NodeSetStatus", propOrder = {
        "value"
})
public class NodeSetStatus {

    @XmlValue
    protected String value;
    @XmlAttribute(name = "Code")
    @XmlSchemaType(name = "unsignedInt")
    protected Long code;

    /**
     * Gets the value of the value property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * Gets the value of the code property.
     *
     * @return possible object is
     * {@link Long }
     */
    public long getCode() {
        if (code == null) {
            return 0L;
        } else {
            return code;
        }
    }

    /**
     * Sets the value of the code property.
     *
     * @param value allowed object is
     *              {@link Long }
     */
    public void setCode(Long value) {
        this.code = value;
    }

}
