//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.03.15 at 12:19:21 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://opcfoundation.org/UA/2011/03/UANodeSet.xsd", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.bytemeistercoding.opcua.uanodeset;
