//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.03.15 at 12:19:21 PM CET 
//


package com.bytemeistercoding.opcua.uanodeset;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for UAInstance complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="UAInstance">
 *   &lt;complexContent>
 *     &lt;extension base="{http://opcfoundation.org/UA/2011/03/UANodeSet.xsd}UANode">
 *       &lt;attribute name="ParentNodeId" type="{http://opcfoundation.org/UA/2011/03/UANodeSet.xsd}NodeId" />
 *       &lt;attribute name="DesignToolOnly" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "UAInstance")
@XmlSeeAlso({
        UAObject.class,
        UAVariable.class,
        UAMethod.class,
        UAView.class
})
public class UAInstance
        extends UANode {

    @XmlAttribute(name = "ParentNodeId")
    protected String parentNodeId;
    @XmlAttribute(name = "DesignToolOnly")
    protected Boolean designToolOnly;

    /**
     * Gets the value of the parentNodeId property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getParentNodeId() {
        return parentNodeId;
    }

    /**
     * Sets the value of the parentNodeId property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setParentNodeId(String value) {
        this.parentNodeId = value;
    }

    /**
     * Gets the value of the designToolOnly property.
     *
     * @return possible object is
     * {@link Boolean }
     */
    public boolean isDesignToolOnly() {
        if (designToolOnly == null) {
            return false;
        } else {
            return designToolOnly;
        }
    }

    /**
     * Sets the value of the designToolOnly property.
     *
     * @param value allowed object is
     *              {@link Boolean }
     */
    public void setDesignToolOnly(Boolean value) {
        this.designToolOnly = value;
    }

}
