//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.03.15 at 12:19:21 PM CET 
//


package com.bytemeistercoding.opcua.uanodeset;

import javax.xml.bind.annotation.*;
import javax.xml.datatype.XMLGregorianCalendar;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="NamespaceUris" type="{http://opcfoundation.org/UA/2011/03/UANodeSet.xsd}UriTable" minOccurs="0"/>
 *         &lt;element name="ServerUris" type="{http://opcfoundation.org/UA/2011/03/UANodeSet.xsd}UriTable" minOccurs="0"/>
 *         &lt;element name="Models" type="{http://opcfoundation.org/UA/2011/03/UANodeSet.xsd}UAModelTable" minOccurs="0"/>
 *         &lt;element name="Aliases" type="{http://opcfoundation.org/UA/2011/03/UANodeSet.xsd}AliasTable" minOccurs="0"/>
 *         &lt;element name="Extensions" type="{http://opcfoundation.org/UA/2011/03/UANodeSet.xsd}ListOfExtensions" minOccurs="0"/>
 *         &lt;choice maxOccurs="unbounded" minOccurs="0">
 *           &lt;element name="UAObject" type="{http://opcfoundation.org/UA/2011/03/UANodeSet.xsd}UAObject"/>
 *           &lt;element name="UAVariable" type="{http://opcfoundation.org/UA/2011/03/UANodeSet.xsd}UAVariable"/>
 *           &lt;element name="UAMethod" type="{http://opcfoundation.org/UA/2011/03/UANodeSet.xsd}UAMethod"/>
 *           &lt;element name="UAView" type="{http://opcfoundation.org/UA/2011/03/UANodeSet.xsd}UAView"/>
 *           &lt;element name="UAObjectType" type="{http://opcfoundation.org/UA/2011/03/UANodeSet.xsd}UAObjectType"/>
 *           &lt;element name="UAVariableType" type="{http://opcfoundation.org/UA/2011/03/UANodeSet.xsd}UAVariableType"/>
 *           &lt;element name="UADataType" type="{http://opcfoundation.org/UA/2011/03/UANodeSet.xsd}UADataType"/>
 *           &lt;element name="UAReferenceType" type="{http://opcfoundation.org/UA/2011/03/UANodeSet.xsd}UAReferenceType"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *       &lt;attribute name="LastModified" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
        "namespaceUris",
        "serverUris",
        "models",
        "aliases",
        "extensions",
        "uaNodes"
})
@XmlRootElement(name = "UANodeSet")
public class UANodeSet {

    @XmlElement(name = "NamespaceUris")
    protected UriTable namespaceUris;
    @XmlElement(name = "ServerUris")
    protected UriTable serverUris;
    @XmlElement(name = "Models")
    protected UAModelTable models;
    @XmlElement(name = "Aliases")
    protected AliasTable aliases;
    @XmlElement(name = "Extensions")
    protected ListOfExtensions extensions;
    @XmlElements({
            @XmlElement(name = "UAObject", type = UAObject.class),
            @XmlElement(name = "UAVariable", type = UAVariable.class),
            @XmlElement(name = "UAMethod", type = UAMethod.class),
            @XmlElement(name = "UAView", type = UAView.class),
            @XmlElement(name = "UAObjectType", type = UAObjectType.class),
            @XmlElement(name = "UAVariableType", type = UAVariableType.class),
            @XmlElement(name = "UADataType", type = UADataType.class),
            @XmlElement(name = "UAReferenceType", type = UAReferenceType.class)
    })
    protected List<UANode> uaNodes;
    @XmlAttribute(name = "LastModified")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar lastModified;

    /**
     * Gets the value of the namespaceUris property.
     *
     * @return possible object is
     * {@link UriTable }
     */
    public UriTable getNamespaceUris() {
        return namespaceUris;
    }

    /**
     * Sets the value of the namespaceUris property.
     *
     * @param value allowed object is
     *              {@link UriTable }
     */
    public void setNamespaceUris(UriTable value) {
        this.namespaceUris = value;
    }

    /**
     * Gets the value of the serverUris property.
     *
     * @return possible object is
     * {@link UriTable }
     */
    public UriTable getServerUris() {
        return serverUris;
    }

    /**
     * Sets the value of the serverUris property.
     *
     * @param value allowed object is
     *              {@link UriTable }
     */
    public void setServerUris(UriTable value) {
        this.serverUris = value;
    }

    /**
     * Gets the value of the models property.
     *
     * @return possible object is
     * {@link UAModelTable }
     */
    public UAModelTable getModels() {
        return models;
    }

    /**
     * Sets the value of the models property.
     *
     * @param value allowed object is
     *              {@link UAModelTable }
     */
    public void setModels(UAModelTable value) {
        this.models = value;
    }

    /**
     * Gets the value of the aliases property.
     *
     * @return possible object is
     * {@link AliasTable }
     */
    public AliasTable getAliases() {
        return aliases;
    }

    /**
     * Sets the value of the aliases property.
     *
     * @param value allowed object is
     *              {@link AliasTable }
     */
    public void setAliases(AliasTable value) {
        this.aliases = value;
    }

    /**
     * Gets the value of the extensions property.
     *
     * @return possible object is
     * {@link ListOfExtensions }
     */
    public ListOfExtensions getExtensions() {
        return extensions;
    }

    /**
     * Sets the value of the extensions property.
     *
     * @param value allowed object is
     *              {@link ListOfExtensions }
     */
    public void setExtensions(ListOfExtensions value) {
        this.extensions = value;
    }

    /**
     * Gets the value of the uaNodes property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the uaNodes property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getUAObjectOrUAVariableOrUAMethod().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link UAObject }
     * {@link UAVariable }
     * {@link UAMethod }
     * {@link UAView }
     * {@link UAObjectType }
     * {@link UAVariableType }
     * {@link UADataType }
     * {@link UAReferenceType }
     */
    public List<UANode> getUaNodes() {
        if (uaNodes == null) {
            uaNodes = new ArrayList<UANode>();
        }
        return this.uaNodes;
    }

    /**
     * Gets the value of the lastModified property.
     *
     * @return possible object is
     * {@link XMLGregorianCalendar }
     */
    public XMLGregorianCalendar getLastModified() {
        return lastModified;
    }

    /**
     * Sets the value of the lastModified property.
     *
     * @param value allowed object is
     *              {@link XMLGregorianCalendar }
     */
    public void setLastModified(XMLGregorianCalendar value) {
        this.lastModified = value;
    }

}
