//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.03.15 at 12:19:21 PM CET 
//


package com.bytemeistercoding.opcua.uanodeset;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for UAType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="UAType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://opcfoundation.org/UA/2011/03/UANodeSet.xsd}UANode">
 *       &lt;attribute name="IsAbstract" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "UAType")
@XmlSeeAlso({
        UAObjectType.class,
        UAVariableType.class,
        UADataType.class,
        UAReferenceType.class
})
public class UAType
        extends UANode {

    @XmlAttribute(name = "IsAbstract")
    protected Boolean isAbstract;

    /**
     * Gets the value of the isAbstract property.
     *
     * @return possible object is
     * {@link Boolean }
     */
    public boolean isAbstract() {
        if (isAbstract == null) {
            return false;
        } else {
            return isAbstract;
        }
    }

    /**
     * Sets the value of the isAbstract property.
     *
     * @param value allowed object is
     *              {@link Boolean }
     */
    public void setIsAbstract(Boolean value) {
        this.isAbstract = value;
    }

}
